Cloud MQTT Broker support
Enable secure, encrypted transmission of user-defined JK-BMS entities to a cloud broker such as HiveMQTT.

As a result, this data can be accessed anywhere in the world and on any device that has an MQTT client installed

diff --git a/rootfs/etc/s6-overlay/s6-rc.d/init-nodered/run b/rootfs/etc/s6-overlay/s6-rc.d/init-nodered/run
--- a/rootfs/etc/s6-overlay/s6-rc.d/init-nodered/run
+++ b/rootfs/etc/s6-overlay/s6-rc.d/init-nodered/run
@@ -2,114 +2,64 @@
 # shellcheck shell=bash
 # ==============================================================================
 # Home Assistant Community Add-on: Node-RED
-# Configures Node-RED before running
+# Configure Node-RED avant exécution
 # ==============================================================================
-declare port
 
-# Migrate add-on data from the Home Assistant config folder,
-# to the add-on configuration folder.
-#if ! bashio::fs.file_exists '/config/settings.js' \
-#    && bashio::fs.file_exists '/homeassistant/node-red/settings.js'; then
-#    shopt -s dotglob
-#    mv /homeassistant/node-red/* /config/ \
-#        || bashio::exit.nok "Failed to migrate Node-RED configuration"
-#fi
-
-# Ensure configuration exists
+# Assure que la configuration existe
 if ! bashio::fs.directory_exists '/config/smartphoton_jkbms/'; then
     mkdir -p /config/smartphoton_jkbms/nodes \
         || bashio::exit.nok "Failed to create node-red configuration directory"
 
-    # Copy in template files
+    # Copie les fichiers modèles
     cp /etc/node-red/flows.json /config/smartphoton_jkbms/
     cp /etc/node-red/settings.js /config/smartphoton_jkbms/
 
-
-    # Create random flow id
+    # Création d'un ID de flow aléatoire
     id=$(node -e "console.log((1+Math.random()*4294967295).toString(16));")
     sed -i "s/%%ID%%/${id}/" "/config/smartphoton_jkbms/flows.json"
 fi
 
-# Vérification de version
-if ! bashio::fs.file_exists '/config/smartphoton_jkbms/version'; then
-  touch /config/smartphoton_jkbms/version
-  VERSION=$(bashio::addon.version)
-  echo $VERSION >> /config/smartphoton_jkbms/version
-  chmod 775 /config/smartphoton_jkbms/version
-  bashio::log.info "${VERSION}"
-
-else
-
-  VERSIONOLD=$(cat /config/smartphoton_jkbms/version)
-  VERSION=$(bashio::addon.version)
-
-  if [ $VERSIONOLD != $VERSION ]; then
-
-    bashio::log.info "Mise a jour de la nouvelle version"
-
-    if bashio::fs.file_exists '/config/smartphoton_jkbms/flows.backup'; then
-      rm /config/smartphoton_jkbms/flows.backup
-    fi
-	mv /config/smartphoton_jkbms/flows.json /config/smartphoton_jkbms/flows.backup
-	cp /etc/node-red/flows.json /config/smartphoton_jkbms/
-
-	#if bashio::fs.file_exists '/config/.storage/lovelace.dashboard_smartphoton.backup'; then
-    #  rm /config/.storage/lovelace.dashboard_smartphoton.backup
-    #fi
-	#if bashio::fs.file_exists '/config/.storage/lovelace.dashboard_smartphoton'; then
-    #  mv /config/.storage/lovelace.dashboard_smartphoton /config/.storage/lovelace.dashboard_smartphoton.backup
-	#  cp /etc/node-red/lovelace.dashboard_smartphoton /config/.storage/
-    #fi
-
-  fi
-
+# Copier le fichier configentities_list.json s'il n'existe pas déjà 
+# Il est utilisé pour le MQTT Cloud
+if ! bashio::fs.file_exists '/config/smartphoton_jkbms/configentities_list.json'; then
+    cp /opt/configentities_list.json /config/configentities_list.json \
+        || bashio::exit.nok "Failed to copy configentities_list.json"
+    bashio::log.info "configentities_list.json copied to /config/"
 fi
 
-#Remplace le fichier flows par celui d'origine
+# Vérification de version
+if ! bashio::fs.file_exists '/config/smartphoton_jkbms/version'; then
+    touch /config/smartphoton_jkbms/version
+    VERSION=$(bashio::addon.version)
+    echo $VERSION >> /config/smartphoton_jkbms/version
+    chmod 775 /config/smartphoton_jkbms/version
+    bashio::log.info "${VERSION}"
+else
+    VERSIONOLD=$(cat /config/smartphoton_jkbms/version)
+    VERSION=$(bashio::addon.version)
+    if [ $VERSIONOLD != $VERSION ]; then
+        bashio::log.info "Mise a jour de la nouvelle version"
+        if bashio::fs.file_exists '/config/smartphoton_jkbms/flows.backup'; then
+            rm /config/smartphoton_jkbms/flows.backup
+        fi
+        mv /config/smartphoton_jkbms/flows.json /config/smartphoton_jkbms/flows.backup
+        cp /etc/node-red/flows.json /config/smartphoton_jkbms/
+    fi
+fi
+
+# Remplace le fichier flows par celui d'origine
 if bashio::fs.file_exists '/config/smartphoton_jkbms/flows.backup'; then
-      rm /config/smartphoton_jkbms/flows.backup
+    rm /config/smartphoton_jkbms/flows.backup
 fi
 mv /config/smartphoton_jkbms/flows.json /config/smartphoton_jkbms/flows.backup
 cp /etc/node-red/flows.json /config/smartphoton_jkbms/
 
-
-
-
-if bashio::fs.file_exists '/config/smartphoton_jkbms/elfinOnduleur'; then
-	rm /config/smartphoton_jkbms/elfinOnduleur
-fi
-
-
-if bashio::fs.file_exists '/config/smartphoton_jkbms/elfinBatterie'; then
-	rm /config/smartphoton_jkbms/elfinBatterie
-fi
-
-
-# Pass in port & SSL settings
-port=$(bashio::addon.port 80)
-sed -i "s/%%PORT%%/${port:-80}/" "/opt/node_modules/node-red-dashboard/nodes/ui_base.html"
-if ! bashio::var.has_value "${port}"; then
-    bashio::log.warning
-    bashio::log.warning "Direct access mode is disabled, Node-RED Dashboard"
-    bashio::log.warning "will not work!"
-    bashio::log.warning
-    bashio::log.warning "Please assign a port in the Network section of this"
-    bashio::log.warning "add-on configuration."
-    bashio::log.warning
-fi
-
-if bashio::config.true 'ssl'; then
-    sed -i "s/%%SSL%%/true/" "/opt/node_modules/node-red-dashboard/nodes/ui_base.html"
-else
-    sed -i "s/%%SSL%%/false/" "/opt/node_modules/node-red-dashboard/nodes/ui_base.html"
-fi
-
-# Ensures conflicting Node-RED packages are absent
+# Désinstallation des packages Node-RED conflictuels
 cd /config || bashio::exit.nok "Could not change directory to Node-RED"
 if bashio::fs.file_exists "/config/package.json"; then
     npm uninstall \
         node-red-contrib-home-assistant \
         node-red-contrib-home-assistant-llat \
         node-red-contrib-home-assistant-ws \
-            || bashio::log.warning "Failed un-installing conflicting packages"
+        || bashio::log.warning "Failed un-installing conflicting packages"
 fi
